name: Process CodeRabbit Reviews

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  debug-comment:
    name: Debug Comment Information
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Output Comment Details
        run: |
          echo "Comment author: ${{ github.event.comment.user.login }}"
          echo "PR number: ${{ github.event.issue.number }}"
          echo "Comment URL: ${{ github.event.comment.html_url }}"
          echo "Comment ID: ${{ github.event.comment.id }}"

  process-coderabbit-review:
    name: Process CodeRabbit Review
    # Fixed condition that checks for several possible variations of the coderabbit username
    if: >-
      github.event.issue.pull_request && 
      (github.event.comment.user.login == 'coderabbitai' || 
       github.event.comment.user.login == 'CodeRabbitAI' || 
       github.event.comment.user.login == 'coderabbit' || 
       github.event.comment.user.login == 'CodeRabbit' || 
       contains(github.event.comment.user.login, 'coderabbit'))
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Review Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            console.log("Processing potential CodeRabbit review comment");
            console.log(`Comment author: ${context.payload.comment.user.login}`);
            
            // Get the PR number from the issue event
            const prNumber = context.payload.issue.number;
            const commentBody = context.payload.comment.body;
            
            // Log the full comment body for debugging
            console.log("Full comment body:");
            console.log(commentBody);
            
            // More flexible check for CodeRabbit review comments
            if (!commentBody.toLowerCase().includes('review') && 
                !commentBody.toLowerCase().includes('coderabbit')) {
              console.log("Comment doesn't appear to be a CodeRabbit review, but continuing anyway");
            }
            
            console.log("Processing as CodeRabbit review comment");
            
            // Determine the review outcome with more flexible matching
            let label = 'needs-review';
            const lowerBody = commentBody.toLowerCase();
            
            if (lowerBody.includes('looks good') || 
                lowerBody.includes('lgtm') ||
                lowerBody.includes('all good') ||
                lowerBody.includes('approved') ||
                lowerBody.includes('no issues')) {
              label = 'approved';
              console.log("Review outcome: approved");
            } else if (lowerBody.includes('issues found') || 
                      lowerBody.includes('needs improvement') ||
                      lowerBody.includes('changes requested') ||
                      lowerBody.includes('fix') ||
                      lowerBody.includes('problem')) {
              label = 'needs-changes';
              console.log("Review outcome: needs changes");
            }
            
            try {
              // Remove the pending label if it exists
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  name: 'review-pending'
                });
                console.log("Removed 'review-pending' label");
              } catch (error) {
                // It's okay if the label doesn't exist
                console.log("Note: Could not remove 'review-pending' label, it may not exist");
              }
              
              // Add the appropriate label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: [label]
              });
              console.log(`Added '${label}' label to PR #${prNumber}`);
              
            } catch (error) {
              console.error("Error processing review:", error);
            }
            
      - name: Send Slack Notification for Completed Review
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "CodeRabbit review completed for PR #${{ github.event.issue.number }}\nAuthor: ${{ github.event.comment.user.login }}\nURL: ${{ github.event.comment.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}