name: CodeRabbit Review Bot

on:
  pull_request:
    types: [opened]

jobs:
  post-coderabbit-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post @coderabbitai comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = '@coderabbitai review';
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body
            });